"use client";
import {useMemo,useState} from "react";
const initial=[
{id:1,admission:"BGK-1001",name:"Aarav Shah",cls:"5-A",parent:"Rakesh Shah",mobile:"9876500001",annual:24000},
{id:2,admission:"BGK-1002",name:"Ayesha Khan",cls:"5-A",parent:"Imran Khan",mobile:"9876500002",annual:24000},
{id:3,admission:"BGK-1003",name:"Vihaan Patel",cls:"7-B",parent:"Nilesh Patel",mobile:"9876500003",annual:30000},
{id:4,admission:"BGK-1004",name:"Fatima Bohra",cls:"7-B",parent:"Mustafa Bohra",mobile:"9876500004",annual:30000},
{id:5,admission:"BGK-1005",name:"Zoya Mamula",cls:"9-A",parent:"Yusuf Mamula",mobile:"9876500005",annual:36000}];
const initialPayments=[
{id:1,receipt:"R-2026-001",student:1,date:"2026-10-07",mode:"UPI",amount:8000},
{id:2,receipt:"R-2026-002",student:2,date:"2026-10-06",mode:"Cash",amount:12000},
{id:3,receipt:"R-2026-003",student:3,date:"2026-10-05",mode:"Bank Transfer",amount:10000},
{id:4,receipt:"R-2026-004",student:4,date:"2026-10-04",mode:"Cash",amount:5000}];
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
function Table({students,paid}){return <div className="tablewrap"><table><thead><tr><th>Student</th><th>Class</th><th>Parent / Mobile</th><th>Demand</th><th>Paid</th><th>Pending</th></tr></thead><tbody>{students.map(s=>{let p=paid[s.id]||0,d=Math.max(0,s.annual-p);return <tr key={s.id}><td><b>{s.name}</b><small>{s.admission}</small></td><td>{s.cls}</td><td>{s.parent}<small>{s.mobile}</small></td><td>{money(s.annual)}</td><td>{money(p)}</td><td className={d?"danger":""}><b>{money(d)}</b></td></tr>})}</tbody></table></div>}
function Card({title,value,danger}){return <div className="card"><span>{title}</span><strong className={danger?"danger":""}>{value}</strong></div>}
export default function ERP(){
const [students,setStudents]=useState(initial),[payments,setPayments]=useState(initialPayments),[tab,setTab]=useState("Dashboard"),[search,setSearch]=useState(""),[add,setAdd]=useState(false),[form,setForm]=useState({admission:"",name:"",cls:"1-A",parent:"",mobile:"",annual:""}),[pay,setPay]=useState({student:1,amount:"",mode:"Cash",date:new Date().toISOString().slice(0,10)});
const paid=useMemo(()=>{let x={};payments.forEach(p=>x[p.student]=(x[p.student]||0)+p.amount);return x},[payments]);
const demand=students.reduce((a,s)=>a+s.annual,0),collected=payments.reduce((a,p)=>a+p.amount,0),pending=demand-collected;
const filtered=students.filter(s=>(s.name+s.admission+s.cls+s.parent).toLowerCase().includes(search.toLowerCase()));
function addStudent(e){e.preventDefault();if(!form.name||!form.admission)return;setStudents([...students,{...form,id:Date.now(),annual:Number(form.annual||0)}]);setForm({admission:"",name:"",cls:"1-A",parent:"",mobile:"",annual:""});setAdd(false)}
function collect(e){e.preventDefault();let amount=Number(pay.amount);if(!amount)return;setPayments([...payments,{id:Date.now(),receipt:"R-"+Date.now(),student:Number(pay.student),date:pay.date,mode:pay.mode,amount}]);setPay({...pay,amount:""});alert("Payment saved. Receipt generated.")}
function csv(){let rows=[["Admission","Student","Class","Parent","Mobile","Demand","Paid","Pending"],...students.map(s=>[s.admission,s.name,s.cls,s.parent,s.mobile,s.annual,paid[s.id]||0,Math.max(0,s.annual-(paid[s.id]||0))])];let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"}));a.download="blossom-fee-report.csv";a.click()}
const nav=["Dashboard","Students","Collect Fee","Pending Fees","Payments","Fee Structure"];
return <div className="shell"><aside><div className="brand"><div className="logo">B</div><div><b>Blossom ERP</b><small>School Management</small></div></div><div className="school">Blossom Kindergarten Senior Secondary School<br/><span>Banswara, Rajasthan</span></div><nav>{nav.map(n=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}>{n}</button>)}</nav><div className="year">Academic Year<br/><b>2026–27</b></div></aside>
<main><header><div><div className="crumb">Blossom ERP / {tab}</div><h1>{tab}</h1></div><div className="top-actions"><button className="secondary" onClick={csv}>Export CSV</button>{tab==="Students"&&<button onClick={()=>setAdd(true)}>+ Add Student</button>}</div></header>
{tab==="Dashboard"&&<><div className="cards"><Card title="Total Students" value={students.length}/><Card title="Fee Demand" value={money(demand)}/><Card title="Collected" value={money(collected)}/><Card title="Pending Fees" value={money(pending)} danger/></div><div className="grid2"><div className="panel"><h3>Fee Collection Overview</h3><div className="progress"><span style={{width:`${demand?Math.min(100,collected/demand*100):0}%`}}/></div><div className="between"><b>{money(collected)} collected</b><span>{demand?Math.round(collected/demand*100):0}%</span></div><div className="statline"><span>Outstanding</span><b>{money(pending)}</b></div><div className="statline"><span>Students with dues</span><b>{students.filter(s=>s.annual-(paid[s.id]||0)>0).length}</b></div></div><div className="panel"><h3>Quick Actions</h3><div className="quick"><button onClick={()=>setTab("Collect Fee")}>Collect Fee</button><button onClick={()=>setTab("Pending Fees")}>Pending Fees</button><button onClick={()=>setTab("Students")}>Students</button><button onClick={csv}>Download Report</button></div></div></div><div className="panel"><h3>Highest Pending Students</h3><Table students={[...students].sort((a,b)=>(b.annual-(paid[b.id]||0))-(a.annual-(paid[a.id]||0))).slice(0,5)} paid={paid}/></div></>}
{tab==="Students"&&<><div className="toolbar"><input placeholder="Search student, admission, parent or class..." value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setAdd(true)}>+ Add Student</button></div><div className="panel"><h3>{filtered.length} Students</h3><Table students={filtered} paid={paid}/></div></>}
{tab==="Pending Fees"&&<><div className="cards"><Card title="Total Outstanding" value={money(pending)} danger/><Card title="Students Due" value={students.filter(s=>s.annual-(paid[s.id]||0)>0).length}/><Card title="Over ₹10,000 Due" value={students.filter(s=>s.annual-(paid[s.id]||0)>10000).length}/><Card title="Academic Year" value="2026–27"/></div><div className="panel"><h3>Pending Fee List</h3><Table students={students.filter(s=>s.annual-(paid[s.id]||0)>0)} paid={paid}/></div></>}
{tab==="Payments"&&<div className="panel"><h3>Payment History</h3><table><thead><tr><th>Receipt</th><th>Date</th><th>Student</th><th>Mode</th><th>Amount</th></tr></thead><tbody>{payments.slice().reverse().map(p=><tr key={p.id}><td>{p.receipt}</td><td>{p.date}</td><td>{students.find(s=>s.id===p.student)?.name}</td><td>{p.mode}</td><td><b>{money(p.amount)}</b></td></tr>)}</tbody></table></div>}
{tab==="Collect Fee"&&<div className="grid2"><div className="panel"><h3>Record New Payment</h3><form className="form" onSubmit={collect}><label>Student<select value={pay.student} onChange={e=>setPay({...pay,student:e.target.value})}>{students.map(s=><option value={s.id} key={s.id}>{s.name} — {s.admission}</option>)}</select></label><label>Amount<input type="number" min="1" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})}/></label><label>Payment Mode<select value={pay.mode} onChange={e=>setPay({...pay,mode:e.target.value})}><option>Cash</option><option>UPI</option><option>Bank Transfer</option><option>Cheque</option></select></label><label>Date<input type="date" value={pay.date} onChange={e=>setPay({...pay,date:e.target.value})}/></label><button>Save Payment & Generate Receipt</button></form></div><div className="panel"><h3>Selected Student Balance</h3>{(()=>{let s=students.find(x=>x.id===Number(pay.student));let p=paid[s?.id]||0;return s&&<><h2>{s.name}</h2><div className="bigbalance">{money(Math.max(0,s.annual-p))}</div><div className="muted">Pending · Demand {money(s.annual)} · Paid {money(p)}</div></>})()}</div></div>}
{tab==="Fee Structure"&&<div className="panel"><h3>2026–27 Fee Structure</h3><div className="notice">Foundation for class-wise fee heads and installments. Production version should store fee assignments by academic year, class, student and installment.</div><table><thead><tr><th>Fee Head</th><th>Frequency</th><th>Status</th></tr></thead><tbody><tr><td>Tuition Fee</td><td>Monthly</td><td>Active</td></tr><tr><td>Annual Charges</td><td>Annual</td><td>Active</td></tr><tr><td>Transport Fee</td><td>Monthly</td><td>Optional</td></tr><tr><td>Late Fee</td><td>As applicable</td><td>Configurable</td></tr></tbody></table></div>}
{add&&<div className="modal"><div className="modalbox"><div className="between"><h2>Add Student</h2><button className="icon" onClick={()=>setAdd(false)}>×</button></div><form className="form" onSubmit={addStudent}>{[["Admission No.","admission"],["Student Name","name"],["Class & Section","cls"],["Parent Name","parent"],["Mobile","mobile"],["Annual Fee Demand","annual"]].map(([l,k])=><label key={k}>{l}<input required={k==="admission"||k==="name"} type={k==="annual"?"number":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button>Add Student</button></form></div></div>}</main></div>}
